# Personal emoji short codes
# https://unicode.org/emoji/charts/full-emoji-list.html

matches:

  - trigger: ":dead"
    replace: "ğŸ’€"
  - trigger: ":died"
    replace: "â˜ "
  - trigger: ":"
    replace: ""

  - trigger: [":+1", ":ok"]
    replace: "ğŸ‘"
  - trigger: ":shrug"
    replace: "ğŸ¤·"
