# Personal emoji short codes

matches:
  - trigger: ":smile:"
    replace: "ğŸ˜Š"
  - trigger: ":grin:"
    replace: "ğŸ˜„"
  - trigger: ":beam:"
    replace: "ğŸ˜"
  - trigger: ":anxious:"
    replace: "ğŸ˜…"
  - trigger: "::" # TODO
    replace: "ğŸ˜†"
  - trigger: ":lol:"
    replace: "ğŸ˜‚"
  - trigger: ":rofl:"
    replace: "ğŸ¤£"
  - trigger: ":melt:"
    replace: "ğŸ« "
  - trigger: ":wink:"
    replace: "ğŸ˜‰"
  - trigger: ":innocent:"
    replace: "ğŸ˜‡"
  - trigger: "::"
    replace: "ğŸ¥°"
  - trigger: "::"
    replace: "ğŸ˜"
  - trigger: "::"
    replace: "ğŸ¤©"
  - trigger: ":kiss:"
    replace: "ğŸ˜˜"
  - trigger: ":kissed:"
    replace: "ğŸ˜š"
  - trigger: "::"
    replace: "ğŸ¥²"
  - trigger: ":silly:"
    replace: "ğŸ˜œ"
  - trigger: ":crazy:"
    replace: "ğŸ¤ª"
  - trigger: ":ner:"
    replace: "ğŸ˜"
  - trigger: ":hug:"
    replace: "ğŸ¤—"
  - trigger: ":giggle:"
    replace: "ğŸ¤­"
  # - trigger: "::"
  #   replace: "ğŸ«¢"
  - trigger: ":peak:"
    replace: "ğŸ«£"
  - trigger: ":shh:"
    replace: "ğŸ¤«"
  - trigger: ":hmm:"
    replace: "ğŸ¤”"
  - trigger: ":salute:"
    replace: "ğŸ«¡"
  - trigger: ":zip:"
    replace: "ğŸ¤"
  - trigger: ":wut:"
    replace: "ğŸ¤¨"
  - trigger: "::" # TODO
    replace: "ğŸ˜"
  - trigger: ":speechless:"
    replace: "ğŸ˜¶"
  - trigger: "::" # TODO
    replace: "ğŸ«¥"
  - trigger: ":fog:"
    replace: "ğŸ˜¶â€ğŸŒ«ï¸"
  - trigger: "::"
    replace: "ğŸ˜"
  - trigger: ":whatever:"
    replace: "ğŸ˜’"
  - trigger: "::" # TODO
    replace: "ğŸ™„"
  - trigger: ":grimace:"
    replace: "ğŸ˜¬"
  - trigger: ":exhale:"
    replace: "ğŸ˜®â€ğŸ’¨"
  - trigger: ":liar:"
    replace: "ğŸ¤¥"
  - trigger: "::"
    replace: "ğŸ˜Œ"
  - trigger: "::"
    replace: "ğŸ˜”"
  - trigger: ":drool:"
    replace: "ğŸ¤¤"
  - trigger: ":sleep:"
    replace: "ğŸ˜´"
  - trigger: ":mask:"
    replace: "ğŸ˜·"
  - trigger: ":sick:"
    replace: "ğŸ¤’"
  - trigger: ":hurt:"
    replace: "ğŸ¤•"
  - trigger: ":vomit:"
    replace: "ğŸ¤®"
  - trigger: ":sneeze:"
    replace: "ğŸ¤§"
  - trigger: ":hot:"
    replace: "ğŸ¥µ"
  - trigger: ":cold:"
    replace: "ğŸ¥¶"
  - trigger: ":queasy:"
    replace: "ğŸ¥´"
  - trigger: ":ded:"
    replace: "ğŸ˜µ"
  - trigger: ":hypno:"
    replace: "ğŸ˜µâ€ğŸ’«"
  - trigger: ":explode:"
    replace: "ğŸ¤¯"
  - trigger: ":party:"
    replace: "ğŸ¥³"
  - trigger: ":cool:"
    replace: "ğŸ˜"
  - trigger: ":nerd:"
    replace: "ğŸ¤“"
  - trigger: ":suss:"
    replace: "ğŸ§"
  - trigger: ":empathetic:"
    replace: "ğŸ˜•"
  - trigger: ":confused:"
    replace: "ğŸ«¤"
  - trigger: ":sad:"
    replace: "ğŸ™"
  - trigger: ":wow:"
    replace: "ğŸ˜®"
  - trigger: ":woah:"
    replace: "ğŸ˜¯"
  - trigger: ":shocked:"
    replace: "ğŸ˜³"
  - trigger: ":plead:"
    replace: "ğŸ¥º"
  - trigger: "::"
    replace: "ğŸ¥¹"
  - trigger: "::"
    replace: "ğŸ˜¥"
  - trigger: ":tear:"
    replace: "ğŸ˜¢"
  - trigger: ":sob:"
    replace: "ğŸ˜­"
  - trigger: ":scream:"
    replace: "ğŸ˜±"
  - trigger: ":canteven:"
    replace: "ğŸ˜–"
  - trigger: "::"
    replace: "ğŸ˜"
  - trigger: "::"
    replace: "ğŸ˜“"
  - trigger: ":yawn:"
    replace: "ğŸ¥±"
  - trigger: ":fuming:"
    replace: "ğŸ˜¤"
  - trigger: ":angry:"
    replace: "ğŸ˜¡"
  - trigger: ":mad:"
    replace: "ğŸ˜ "
  - trigger: ":fuck:"
    replace: "ğŸ¤¬"
  - trigger: ":cheeky:"
    replace: "ğŸ˜ˆ"