scan_timeout = 100
add_newline = true
palette = 'pride'

format = """
â”€â”€$jobs$character$status$fill$cmd_durationâ”€â”€

[ ${custom.hardware}$os$hostname$shlvl](bg:host_bg fg:#090c0c)\
[î‚°](fg:host_bg bg:tlpwd_bg)\
${custom.tlpwd}\
$git_branch\
[î‚°](fg:tlpwd_bg bg:dir_bg)\
$directory\
[îƒ€](fg:dir_bg)\
$fill\
[îƒ‚](fg:dev_bg) \
$package\
[î‚²](fg:lang_bg bg:dev_bg)\
$c\
$cmake\
$conda\
$dart\
$deno\
$dotnet\
$golang\
$nim\
$nodejs\
[ ï‡‰  ](bg:lang_bg)\
$php\
$python
$rlang\
$rust\
$swift\

$newline
 [î‚¶](fg:5)[ ](bg:5)\
$sudo\
$username\
[î‚°](bg:8 fg:5)\
[î‚°](bg:15 fg:8)\
${custom.prompt}\
[îƒ†](fg:15)  \
"""

right_format = """
$git_status\
$git_commit\
[îƒ‡](fg:5)\
$time\
[î‚´](fg:5) \
"""

# red #de324c
# orange #f4895f
# yellow #f8e16f
# green #95cf92
# blue #369acc
# purple #9656a2

# LGBT Pride!
# LGBT_PROMPT="${LS_RED}îŠ…${LS_YELLOW}îŠ…${LS_GREEN}îŠ…${LS_CYAN}îŠ…${LS_PURPLE}îŠ… ${LS_RESET}"
#

[palettes.pride]
host_bg = "#f4895f"
tlpwd_bg = "#f8e16f"
dir_bg = "#95cf92"
dev_bg = "#369acc"
lang_bg = "#9656a2"

# unsorted = """
# $battery\
# $memory_usage\

# $container\
# $kubernetes\
# $docker_context\
# $helm\

# $aws\
# $azure\
# $gcloud\
# ${custom.oracle}\

# $shell\
# """


# might_use = """
# $bun\
# $env_var\
# $localip\
# $terraform\
# """



# ï±®

# Best effort to show the type of deployment the OS is running on
# ï…º (WSL), ïŒ•, ï…¹, ïƒ‚ (VPS, hypervisor)
[custom.hardware]
command = "echo ïŒ• î‚±"
style = "bg:host_bg fg:#090c0c"
when = false

[custom.prompt]
command = 'beeline-prompt icon'
style = 'bg:15'
format = '[$output]($style)'
when = true

[custom.pwd]
command = 'echo $PWD'
when = true
style = 'green'
format = '[$output]($style)'

[custom.tlpwd]
description = "The most significant top-level directory of your current directory"
command = 'beeline-pwd root | beeline-pretty'
when = true
style = 'bold bg:tlpwd_bg fg:black'
format = '[ $output]($style)'

[custom.quarto]
command = 'echo Quarto'

[custom.arduino]
symbol = ""



[cmd_duration]
min_time = 100
format = '[ ï¨š$duration ]($style)'

[directory]
format = "[ $path ]($style)"
style = "fg:black bg:dir_bg"
read_only = " ó°Œ¾"
home_symbol = ""
truncate_to_repo = false
truncation_length = 1
use_os_path_sep = false

# [directory.substitutions]
# '/' = " î‚± "

[fill]
# symbol = 'â”€'
symbol = ' '

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "ï˜ "
truncation_length = 6
style = "italic bg:tlpwd_bg fg:black"

[git_commit]
only_detached = false
style = 'white'
commit_hash_length = 5
format = '[ï— $hash$tag]($style) '

[git_status]
format = '[$ahead_behind$all_status]($style)'
ignore_submodules = true
conflicted = '[ï¦ $count](red) '
ahead = '[ï¢ $count](green) '
behind = '[ï£ $count](yellow) '
diverged = '[ï½ $ahead_count/$behind_count](purple) ' # Replace with f0641 ó°™
up_to_date = '[ï€Œ  ](green)'
untracked = '[ï§ $count ](blue)'
stashed = '[ïœ¿ $count ](purple)'
modified = '[ï› $count ](yellow)'
staged = '[â— $count ](green)'
renamed = '[ï¥” $count ](yellow)'
deleted = '[ï‡¸ $count ](red)'
typechanged = '[ï± $count ](yellow)'

# TODO: Flag when no remote origin (local only)

[character]
success_symbol = '[ ï€Œ ](bold green) '
error_symbol = '[ ï€ ](bold red) '

[hostname]
format = '[$hostname ]($style)'
style = "bg:host_bg fg:#090c0c"
ssh_only = true

[memory_usage]
symbol = "ó°› "

[os]
disabled = false
style = "bg:host_bg fg:#090c0c"

[package]
symbol = "î¬© "
format = '[ $symbol$version ]($style)'
style = "bg:dev_bg fg:bold"
disabled = false

[shlvl]
disabled = false
style = "bg:host_bg fg:#090c0c"
format = '[î‚± $symbol$shlvl ]($style)'
symbol = 'ï’‰ '

[status]
style = ""
format = '[$maybe_int$common_meaning$signal_name]($style)'
disabled = false

[sudo]
style = 'bold red'
symbol = 'ï„ªï„ª'
format = '[ $symbol ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:5"
format = '[  ï€— $time ]($style)'

[username]
style_user = "fg:#7DF9AA bg:#1C3A5E"
format = '[ ï€‡ $user ]($style)'
show_always = false

## Envirnoments

[aws]
symbol = "îŒ½  "
[docker_context]
symbol = "ïŒˆ "

## Languages

[c]
symbol = "î˜ "
format = '[$symbol($version(-$name) )]($style)'
style= 'bg:lang_bg fg:bold'
[cmake]
symbol = "î™³ "
style= 'bg:lang_bg fg:bold'
[conda]
symbol = "ğŸ…’ "
style= 'bg:lang_bg fg:bold'
[dart]
symbol = "î˜ "
format = '[$symbol($version )]($style)'
style= 'bg:lang_bg fg:bold'
[deno]
symbol = "ğŸ¦• "
format = '[$symbol($version )]($style)'
style= 'bg:lang_bg fg:bold'
[dotnet]
symbol = ".NET "
format = '[$symbol($version )]($style)'
style= 'bg:lang_bg fg:bold'
[golang]
symbol = "î˜§ "
format = '[$symbol($version )]($style)'
style= 'bg:lang_bg fg:bold'
[nim]
symbol = "î™· "
format = '[$symbol($version )î‚³ ]($style)'
style= 'bg:lang_bg fg:bold'
[nodejs]
symbol = "îœ˜ "
format = '[$symbol](bg:lang_bg fg:green)[($version )î‚³]($style)'
style= 'bg:lang_bg fg:bold green'
[php]
symbol = "îœ½ "
style= 'bg:lang_bg fg:bold'
[python]
symbol = "î˜† "
style= 'bg:lang_bg fg:bold'
[rlang]
symbol = "ó°Ÿ” "
style= 'bg:lang_bg fg:bold'
[rust]
symbol = "î¨ "
style= 'bg:lang_bg fg:bold'
[swift]
symbol = "î• "
style= 'bg:lang_bg fg:bold'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
# Garuda = "ó°›“ "
Gentoo = "ïŒ "
# HardenedBSD = "ó°Œ "
# Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
# OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
# OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
# Redox = "ó°€˜ "
# Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ï™ "
Windows = "ï…º "
# TODO: Rocky Linux



# Icon set: https://www.nerdfonts.com/cheat-sheet

# B6_ICON_GENERIC_COMMENT="ïŠ’"
# B6_ICON_GENERIC_USER="ï€‡"
# B6_ICON_GENERIC_SUPERUSER="ï„ªï„ª"
# B6_ICON_GENERIC_WINDOWS="ï‹’"
# B6_ICON_GENERIC_CLOCK="ï€—"
# B6_ICON_GENERIC_STOPWATCH="ï¨š"
# B6_ICON_GENERIC_CALENDER="ï³"
# B6_ICON_GENERIC_NOTIFICATION="ï–"
# B6_ICON_GENERIC_CHAT="ïƒ¦"
# B6_ICON_GENERIC_GLOBE="ïª"
# B6_ICON_GENERIC_EMAIL="ï«¯"
# B6_ICON_GENERIC_PLAYING="ï€"
# B6_ICON_GENERIC_PAUSED="ïŠŒ"
# B6_ICON_GENERIC_INCOGNITO="ïˆ›"
# B6_ICON_GENERIC_SUCCESS="ï€Œ"
# B6_ICON_GENERIC_ERROR="ï€"
# B6_ICON_GENERIC_WARNING="ï±"
# B6_ICON_GENERIC_LOADING="ï›—"
# B6_ICON_GENERIC_PROMPT="ï¬¦" # Common alternative options: ï¬¦, ï„ , ï…•îŠ…
# B6_ICON_GENERIC_DIVIDER="â”€"



# export B6_ICON_GIT_CONFLICT="ï¦"
# export B6_ICON_GIT_AHEAD="ï¢"
# export B6_ICON_GIT_BEHIND="ï£"
# export B6_ICON_GIT_DIVERGED="ï½ or ï‘€"
# export B6_ICON_GIT_CLEAN="${B6_ICON_GENERIC_SUCCESS}"
# export B6_ICON_GIT_UNTRACKED="â—"
# export B6_ICON_GIT_STASHED="ïœ¿"
# export B6_ICON_GIT_MODIFIED="ï›"
# export B6_ICON_GIT_STAGED="ï§"
# export B6_ICON_GIT_RENAMED="ï¥”"
# export B6_ICON_GIT_DELETED="ï‡¸"

# Check for skynet

# if [ -n "$BEELINE_DISABLE_SKYNET" ]; then
#   export LAST_CMD_EXIT_CODE=$?
# elif [ -n "$BEELINE_DISABLE_SKYNET_WARNING" ]; then
#   echo "Skynet is disabled! Good luck hoomaan!"
# fi




# Unused modules

# $buf\
# $cobol\
# $crystal\
# $daml\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $fossil_branch\
# $git_metrics\
# $gradle\
# $haskell\
# $haxe\
# $java\
# $julia\
# $kotlin\
# $lua\
# $meson\
# $hg_branch\
# $nix_shell\
# $opa\
# $openstack\
# $ocaml\
# $perl\
# $pijul_channel\
# $pulumi\
# $purescript\
# $raku\
# $red\
# $ruby\
# $scala\
# $singularity
# $solidity\
# $spack\
# $vagrant\
# $vlang\
# $vcsh\
# $zig\